services:
  mysql:
    container_name: mysql_fleetTrack
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fleetTrack_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fleetTrack-net
    restart: unless-stopped

networks:
  fleetTrack-net:
    driver: bridge

volumes:
  mysql_data: